//! The embedded doc corpus and per-file overrides.
//!
//! The `languages/` principle/metric Markdown is compiled into the binary (see
//! `build.rs`), so the tool can serve a doc's text directly (`report --doc HK`)
//! without a network fetch. A project may substitute any one fragment via
//! `[templates.languages.<lang>.<ID>]` (read from disk instead of the embedded
//! copy) — the doc analogue of overriding a config key.

use crate::config::TemplatesConfig;
use anyhow::{Context, Result};
use code_ranker_graph::snapshot::Snapshot;

// `CORPUS: &[(&str, &str)]` — `(<lang>/<ID>.md, contents)` — generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/corpus.rs"));

/// The embedded contents of a corpus doc by its `<lang>/<ID>.md` relative path.
fn corpus_doc(rel: &str) -> Option<&'static str> {
    CORPUS.iter().find(|(k, _)| *k == rel).map(|(_, v)| *v)
}

/// The corpus path a doc id resolves to, as `<lang>/<ID>.md` — read from the
/// already-resolved `doc_url` of a matching principle (principle docs) or the
/// `remediation` URL of a matching metric (coupling/complexity docs). Both encode
/// the post-fallback corpus location (own `<lang>/` or the shared `base/`), so the
/// override key namespace lines up with where the doc actually lives.
fn doc_rel_path(snap: &Snapshot, id: &str) -> Option<String> {
    // `cycle` is the ADP principle's metric lens (not a real node attribute), so
    // its doc IS the ADP doc — resolve it through the ADP principle below.
    let id = if id.eq_ignore_ascii_case("cycle") {
        "ADP"
    } else {
        id
    };
    // Principle (case-insensitive id, e.g. `SRP`, `adp`).
    if let Some(p) = snap
        .principles
        .iter()
        .find(|p| p.id.eq_ignore_ascii_case(id))
        && let Some(url) = &p.doc_url
        && let Some(rel) = url_tail(url)
    {
        return Some(rel);
    }
    // Metric doc: the attribute is found by its (lowercase) key, but the canonical
    // doc filename comes from the `--doc <ID>` token in its `remediation` (e.g. key
    // `fan_in` → doc `Fan-in.md`). Metric docs live in the neutral `base/` corpus.
    let key = id.to_ascii_lowercase();
    if let Some(rel) = snap
        .graphs
        .get("files")
        .and_then(|f| f.node_attributes.get(&key))
        .and_then(|spec| spec.remediation.as_deref())
        .and_then(crate::recommend::doc_ref)
        .map(|doc| format!("base/{doc}.md"))
    {
        return Some(rel);
    }
    // Fallback: any base corpus doc addressable by its filename stem
    // (case-insensitive) — covers docs that are neither a principle nor a metric:
    // `Fan-in` / `Fan-out` (key is `fan_in`, not the hyphenated filename), the
    // `metrics` reference, and the `AI` overview index.
    CORPUS.iter().find_map(|(rel, _)| {
        let stem = rel.strip_prefix("base/")?.strip_suffix(".md")?;
        stem.eq_ignore_ascii_case(id).then(|| (*rel).to_string())
    })
}

/// Extract the `<lang>/<ID>.md` tail of a corpus URL (`…/languages/base/HK.md`
/// → `base/HK.md`). A `remediation` value is free prose ending in the URL, so the
/// match is anchored on the `/languages/` segment, not the string start.
fn url_tail(url: &str) -> Option<String> {
    let after = url.rsplit_once("/languages/")?.1;
    // Stop at whitespace in case the URL is embedded in a sentence.
    Some(after.split_whitespace().next()?.to_string())
}

/// A language doc is a **manifest** (assembled from the base) when it carries at
/// least one `<!-- doc:base … -->` include; a full standalone doc has none and is
/// served verbatim. (A manifest may still write its own `# ` H1 + TL;DR head.)
fn is_manifest(md: &str) -> bool {
    md.contains("<!-- doc:base")
}

/// Marker placed in `base/AI.md`; expands to a one-paragraph summary of every
/// other base doc (its `**TL;DR**` paragraph, or the first prose paragraph when a
/// doc has none), so the AI overview always lists the current catalog.
const TLDR_INDEX_MARKER: &str = "<!-- doc:tldr-index -->";

/// A base doc's one-paragraph summary for the index: its `**TL;DR**` paragraph
/// (lines from the `**TL;DR**` line to the next blank line, joined into one), or
/// the first prose paragraph after the H1 when there is no explicit TL;DR.
fn doc_summary(md: &str) -> Option<String> {
    let lines: Vec<&str> = md.lines().collect();
    let para_from = |start: usize| -> Option<String> {
        let mut buf = Vec::new();
        for l in &lines[start..] {
            let t = l.trim();
            if t.is_empty() || t.starts_with('#') {
                if buf.is_empty() {
                    continue;
                }
                break;
            }
            buf.push(t);
        }
        (!buf.is_empty()).then(|| buf.join(" "))
    };
    if let Some(i) = lines
        .iter()
        .position(|l| l.trim_start().starts_with("**TL;DR**"))
    {
        return para_from(i);
    }
    let h1 = lines
        .iter()
        .position(|l| l.starts_with("# "))
        .map_or(0, |i| i + 1);
    para_from(h1)
}

/// Build the catalog the `<!-- doc:tldr-index -->` marker expands to: every
/// `base/<ID>.md` (except `AI.md` itself), alphabetical, each as a `### <title>`
/// heading + a `--doc <ID>` pointer to the full doc + its one-paragraph summary.
fn tldr_index() -> String {
    let mut entries: Vec<(String, String)> = CORPUS
        .iter()
        .filter_map(|(rel, contents)| {
            let stem = rel.strip_prefix("base/")?.strip_suffix(".md")?;
            if stem.eq_ignore_ascii_case("AI") {
                return None;
            }
            let title = contents
                .lines()
                .find_map(|l| l.strip_prefix("# "))
                .unwrap_or(stem)
                .trim();
            let head = format!("### {title}\n\nFull doc: `code-ranker report --doc {stem}`");
            let entry = match doc_summary(contents) {
                Some(s) => format!("{head}\n\n{s}"),
                None => head,
            };
            Some((stem.to_ascii_lowercase(), entry))
        })
        .collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    entries
        .into_iter()
        .map(|(_, e)| e)
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// Replace a `<!-- doc:tldr-index -->` marker with the generated catalog; a no-op
/// for docs that don't carry it.
fn expand_tldr_index(md: &str) -> String {
    if md.contains(TLDR_INDEX_MARKER) {
        md.replace(TLDR_INDEX_MARKER, &tldr_index())
    } else {
        md.to_string()
    }
}

pub(crate) fn resolve_doc(
    snap: &Snapshot,
    templates: &TemplatesConfig,
    id: &str,
) -> Result<String> {
    Ok(expand_tldr_index(&resolve_doc_raw(snap, templates, id)?))
}

/// Resolve the Markdown for doc `id` against the active snapshot. In order:
/// 1. a `[templates.languages.<lang>.<ID>]` override → that file verbatim (the
///    user supplies the final doc, "as if it were `languages/<lang>/<ID>.md`");
/// 2. a language **manifest** (`<lang>/<ID>.md` with `<!-- doc:base … -->` includes)
///    → assembled from `base/<ID>.md` by [`crate::compose::compose`];
/// 3. the embedded `<lang>/<ID>.md` (a full standalone doc); else the `base/<ID>.md`
///    fallback.
///
/// `id` is a principle id (`SRP`) or a metric key (`hk`).
fn resolve_doc_raw(snap: &Snapshot, templates: &TemplatesConfig, id: &str) -> Result<String> {
    let rel = doc_rel_path(snap, id).with_context(|| {
        let known: Vec<&str> = snap.principles.iter().map(|p| p.id.as_str()).collect();
        format!(
            "no principle or metric doc for {id:?}. Known principles: {}",
            known.join(", ")
        )
    })?;
    let (lang, file) = rel.split_once('/').unwrap_or(("base", &rel));
    let stem = file.strip_suffix(".md").unwrap_or(file);

    // 1. Override wins: the user's file is the final doc — no composition.
    if let Some(path) = templates.languages.get(lang).and_then(|m| m.get(stem)) {
        return std::fs::read_to_string(path)
            .with_context(|| format!("reading template override {path} for {lang}/{stem}"));
    }

    // 2. A language manifest → assemble it from the neutral base sections. A
    //    `templates.languages.base.<ID>` override substitutes the base here too, so
    //    it flows through into every language that assembles over it.
    if lang != "base"
        && let Some(manifest) = corpus_doc(&rel)
        && is_manifest(manifest)
    {
        let base = match templates.languages.get("base").and_then(|m| m.get(stem)) {
            Some(path) => std::fs::read_to_string(path)
                .with_context(|| format!("reading base template override {path} for {stem}"))?,
            None => corpus_doc(&format!("base/{stem}.md"))
                .with_context(|| format!("manifest {rel} has no base/{stem}.md"))?
                .to_string(),
        };
        return crate::compose::compose(manifest, &base, lang_display(lang));
    }

    // 3. The embedded full doc, else the base fallback.
    corpus_doc(&rel)
        .map(str::to_string)
        .or_else(|| corpus_doc(&format!("base/{stem}.md")).map(str::to_string))
        .with_context(|| format!("doc {rel} is not embedded in this build"))
}

/// Write the published doc corpus into `out_dir` for GitHub Pages: every
/// `base/<ID>.md` copied as-is (the fallback corpus), every language **manifest**
/// (a `<lang>/<ID>.md` carrying `<!-- doc:base … -->` includes) emitted as its
/// assembled doc, and any full `<lang>/<ID>.md` copied through verbatim. Returns the
/// file count.
pub(crate) fn build_corpus(out_dir: &std::path::Path) -> Result<usize> {
    let mut written = 0usize;
    for (rel, contents) in CORPUS {
        let (lang, file) = match rel.split_once('/') {
            Some(p) => p,
            None => continue,
        };
        let stem = file.strip_suffix(".md").unwrap_or(file);

        let body: String = if lang != "base" && is_manifest(contents) {
            // Assemble: the published `<lang>/<ID>.md` is the manifest over base.
            let base = corpus_doc(&format!("base/{stem}.md"))
                .with_context(|| format!("manifest {rel} has no base/{stem}.md"))?;
            crate::compose::compose(contents, base, lang_display(lang))?
        } else {
            // `base/*` and full language docs are published verbatim (the AI index's
            // `<!-- doc:tldr-index -->` marker is expanded so Pages ships the catalog,
            // not the raw marker).
            expand_tldr_index(contents)
        };

        let dest = out_dir.join(rel);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("creating {}", parent.display()))?;
        }
        std::fs::write(&dest, &body).with_context(|| format!("writing {}", dest.display()))?;
        written += 1;
    }
    Ok(written)
}

/// Display name for a corpus language folder, used as the H1 `(in <Lang>)` suffix.
fn lang_display(lang: &str) -> &str {
    match lang {
        "rust" => "Rust",
        "python" => "Python",
        "typescript" => "TypeScript",
        "javascript" => "JavaScript",
        "go" => "Go",
        "c" => "C",
        "cpp" => "C++",
        "csharp" => "C#",
        "markdown" => "Markdown",
        other => other,
    }
}

#[cfg(test)]
#[path = "templates_test.rs"]
mod tests;
